### ISSUE TITLE
Game crashed caused by ArrayIndexOutOfBoundsException on Minecraft

### ISSUE THREAD

**Issue by Ghost-chu** [kyrptonaught/tooltipfix#14]
Random crash:
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2022/1/10 下午9:20
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1025
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.rehash(Int2ObjectOpenHashMap.java:1334)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.insert(Int2ObjectOpenHashMap.java:279)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:500)
	at net.minecraft.class_377.method_2011(class_377.java:102)
	at net.minecraft.class_327.method_27516(class_327.java:55)
	at net.minecraft.class_5225.method_27496(class_5225.java:39)
	at net.minecraft.class_5223.method_27477(class_5223.java:17)
	at net.minecraft.class_5223.method_27473(class_5223.java:120)
	at net.minecraft.class_5223.method_27472(class_5223.java:84)
	at net.minecraft.class_5223.method_27479(class_5223.java:80)
	at net.minecraft.class_5225.method_27482(class_5225.java:38)
	at net.minecraft.class_327.method_1727(class_327.java:362)
	at net.kyrptonaught.tooltipfix.Helper.isTooWide(Helper.java:66)
	at net.kyrptonaught.tooltipfix.Helper.doFix(Helper.java:28)
	at net.minecraft.class_437.redirect$bof000$fixWTTData(class_437.java:2717)
	at net.minecraft.class_437.method_32634(class_437.java:173)
	at net.minecraft.class_437.method_25409(class_437.java:169)
	at net.minecraft.class_481.method_25409(class_481.java:733)
	at net.minecraft.class_465.method_2380(class_465.java:190)
	at net.minecraft.class_481.method_25394(class_481.java:694)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.rehash(Int2ObjectOpenHashMap.java:1334)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.insert(Int2ObjectOpenHashMap.java:279)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:500)
	at net.minecraft.class_377.method_2011(class_377.java:102)
	at net.minecraft.class_327.method_27516(class_327.java:55)
	at net.minecraft.class_5225.method_27496(class_5225.java:39)
	at net.minecraft.class_5223.method_27477(class_5223.java:17)
	at net.minecraft.class_5223.method_27473(class_5223.java:120)
	at net.minecraft.class_5223.method_27472(class_5223.java:84)
	at net.minecraft.class_5223.method_27479(class_5223.java:80)
	at net.minecraft.class_5225.method_27482(class_5225.java:38)
	at net.minecraft.class_327.method_1727(class_327.java:362)
	at net.kyrptonaught.tooltipfix.Helper.isTooWide(Helper.java:66)
	at net.kyrptonaught.tooltipfix.Helper.doFix(Helper.java:28)
	at net.minecraft.class_437.redirect$bof000$fixWTTData(class_437.java:2717)
	at net.minecraft.class_437.method_32634(class_437.java:173)
	at net.minecraft.class_437.method_25409(class_437.java:169)
	at net.minecraft.class_481.method_25409(class_481.java:733)
	at net.minecraft.class_465.method_2380(class_465.java:190)
	at net.minecraft.class_481.method_25394(class_481.java:694)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (193, 75). Absolute: (1158.000000, 454.000000)
	Screen size: Scaled: (427, 249). Absolute: (2560, 1494). Scale factor of 6.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Ghost_chu'/329, l='ClientLevel', x=-94.08, y=66.17, z=91.31]]
	Chunk stats: 4096, 1024
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,88,-1), Section: (at 0,8,15 in 4,5,-1; chunk contains blocks 64,-64,-16 to 79,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 189913 game time, 10171066 day time
	Server brand: §bBilicraft§r§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 154119688 bytes (146 MiB) / 1484783616 bytes (1416 MiB) up to 9026142208 bytes (8608 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x24dd
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1006
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 41288.86
	Virtual memory used (MB): 35297.39
	Swap memory total (MB): 8668.80
	Swap memory used (MB): 361.47
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8601m
	Fabric Mods: 
		alternatecurrent: Alternate Current 1.1.0
		animatica: Animatica 0.3+1.18
		architectury: Architectury 3.4.9
		authme: Auth Me 2.2.0
		beenfo: Beenfo 1.18.1-fabric0.45.0-1.3.3
		bilicraftclientui: Bilicraft Client UI 0.2.16
		bilicraftdanmaku: Bilicraft Danmaku 0.0.4
		citresewn: CITResewn 0.8.2+1.18.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_bilicraft_bilicraftdanmaku-protocol: BilicraftDanmaku-Protocol 1.4-SNAPSHOT
		com_google_guava_guava: guava 31.0.1-jre
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		crowdin-translate: CrowdinTranslate 1.4+1.18
		customlan: Custom LAN 1.18-v2.0.1
		enchantment_lore: Enchantment Lore 1.2.4+MC1.18-1.18.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.18
		entity-distance: Entity Distance Mod 1.0.4
		fabric: Fabric API 0.45.2+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fallingleaves: Falling Leaves 1.8.1+1.18.1
		fix_chat_lag: Non blocking chat 1.0.0
		gbfabrictools: GBfabrictools 1.3.4+1.18
		inspecio: Inspecio 1.2.1+1.18
		iris: Iris 1.1.4
		isometric-renders: Isometric Renders 0.2.11+1.18
		java: OpenJDK 64-Bit Server VM 17
		kappa: Kappa 3.0.2
		krypton: Krypton 0.1.6
		lazydfu: LazyDFU 0.1.2
		minecraft: Minecraft 1.18.1
		modmenu: Mod Menu 3.0.1
		multiconnect: MultiConnect 1.5.10
		multiconnect-api: MultiConnect API 1.5.10
		not-enough-servers: Not Enough Servers 1.0.2
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		oro_config: OroArmor Config 2.1.0
		pinglist: PingList 1.3.3
		sodium: Sodium 0.4.0-alpha5+build.9
		soundphysics: Sound Physics 0.5.2
		starlight: Starlight 1.0.0+fabric.d0a3220
		tooltipfix: ToolTip Fix 1.0.4-1.18
		worldmesher: Worldmesher 0.2.5+1.18
	Launched Version: Bilicraft-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 510.06, NVIDIA Corporation
	Window size: 2560x1494
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: 简体中文 (中国)
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics 
```

**Comment by kyrptonaught** [comment]
Do you know what was being displayed? I'm curious what caused this

**Comment by Ghost-chu** [comment]
> Do you know what was being displayed? I'm curious what caused this

It just crashed while I just fly everywhere, nothing show up, no GUI, just crashed.

**Comment by Laifsyn** [comment]
I got similar issue
https://pastebin.com/VXZXu2iK

https://pastebin.com/g8740AHc
Edit:Second pastebin and formatting
I think it was in the REI SearchBar
```-- Screen render details --
Details:
Screen name: net.minecraft.class_481
	Mouse location: Scaled: (193, 204). Absolute: (580.000000, 614.000000)
	Screen size: Scaled: (534, 300). Absolute: (1600, 900). Scale factor of 3.000000
Stacktrace:```

**Comment by Laifsyn** [comment]
Crashed again
Report:
https://pastebin.com/3QtAgCPy
and latest log
[latest.zip](https://github.com/kyrptonaught/tooltipfix/files/8498880/latest.zip)

**Comment by Laifsyn** [comment]
Hello, so I removed the mod and still crashed. I'll probably submit a ticket to REI instead and see if they can find something
