### ISSUE TITLE
Incompatible with Quilt

### ISSUE THREAD

**Issue by GooberOne** [kyrptonaught/tooltipfix#32]
I've found that Quilt is incompatible with this.

**Comment by ghost** [comment]
Can confirm.
Crash logs show:

```
[08:26:34] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/[REDACTED]/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/c1dc27696aa4006e492c2485c9ccbcb26045a971/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Quilt Env=CLIENT
[08:26:34] [main/ERROR]: Minecraft has crashed!
org.quiltmc.loader.impl.FormattedException: java.lang.IllegalAccessError: failed to access class net.minecraft.unmapped.C_hhxmszuy$C_udznyblk from class net.minecraft.text.component.TextComponent (net.minecraft.unmapped.C_hhxmszuy$C_udznyblk and net.minecraft.text.component.TextComponent are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @68ad99fe)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:425) ~[quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.8.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.8.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.IllegalAccessError: failed to access class net.minecraft.unmapped.C_hhxmszuy$C_udznyblk from class net.minecraft.text.component.TextComponent (net.minecraft.unmapped.C_hhxmszuy$C_udznyblk and net.minecraft.text.component.TextComponent are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @68ad99fe)
	at net.minecraft.text.component.TextComponent.<clinit>(TextComponent.java:11) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.text.Text.translatable(Text.java:440) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.command.TranslatableBuiltInExceptions.<clinit>(TranslatableBuiltInExceptions.java:24) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.SharedConstants.<clinit>(SharedConstants.java:228) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:55) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-project-@-merged-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.8.jar:?]
	... 3 more
```

**Comment by Simsz** [comment]
I am running Quilt 0.25 on Minecraft 1.19.2 and this mod works fine. I am able to run it with no issues. Which version are you running?

**Comment by ghost** [comment]
No idea, I think I messed something up with my mappings, but this is now an old project. @GooberOne they can’t help you if you don’t provide a crash log.
