### ISSUE TITLE
ToolTipFix Crashes when run with Mod Menu

### ISSUE THREAD

**Issue by EricKilla** [kyrptonaught/tooltipfix#7]
```[22:17:04] [main/INFO]: Loading for game Minecraft 1.16.5
[22:17:05] [main/INFO]: [FabricLoader] Loading 48 mods: fabric-screen-handler-api-v1@1.1.1+ca58154a7d, minecraft@1.16.5, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, modmenu@1.16.4, fabric-command-api-v1@1.0.10+ca58154a7d, fabricloader@0.11.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, java@8, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-game-rule-api-v1@1.0.6+ca58154a7d, tooltipfix@1.0.2-1.16.1, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.30.0+1.16, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-particles-v1@0.2.4+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d
[22:17:05] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Aaron%20Lawson/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[22:17:08] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:17:08] [main/INFO]: Setting user: EricKilla
[22:17:09] [main/INFO]: [Indigo] Registering Indigo renderer!
[22:17:09] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[22:17:10] [main/INFO]: Narrator library for x64 successfully loaded
[22:17:10] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Screen Handler API (v1), Fabric Networking Block Entity (v0), Fabric Renderer API (v1), Fabric Key Bindings (v0), Mod Menu, Fabric Command API (v1), Fabric Loader, Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Structure API (v1), Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Crash Report Info (v1), Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Game Rule API (v1), Fabric Entity Events (v1), Fabric API Base, Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Rendering Fluids (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Loot Tables (v1), Fabric API, Fabric Item Groups (v0), Fabric Models (v0), Fabric Particles (v1), Fabric Object Builders (v0), Fabric Networking (v0))
[22:17:14] [main/INFO]: OpenAL initialized.
[22:17:14] [main/INFO]: Sound engine started
[22:17:14] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[22:17:14] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[22:17:14] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:17:14] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:17:14] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22:17:14] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22:17:14] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:17:14] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[22:17:14] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22:17:14] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:17:18] [main/WARN]: Warning! Mod tooltipfix has a broken icon, loading default icon
[22:17:23] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:625) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
Caused by: java.lang.ClassCastException: net.minecraft.class_5481$$Lambda$3305/1498187897 cannot be cast to net.minecraft.class_2561
	at net.kyrptonaught.tooltipfix.Helper.doFix(Helper.java:30) ~[tooltipfix-1.0.2-1.16.1.jar:?]
	at net.minecraft.class_437.handler$zdi000$fix(class_437.java:1555) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_437.method_25417(class_437.java) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_437.method_25424(class_437.java:128) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$2(ModsScreen.java:136) ~[modmenu-1.16.4.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen$$Lambda$3324/404709812.onTooltip(Unknown Source) ~[?:?]
	at net.minecraft.class_4185.method_25352(class_4185.java:47) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuTexturedButtonWidget.method_25359(ModMenuTexturedButtonWidget.java:61) ~[modmenu-1.16.4.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen$1.method_25359(ModsScreen.java:156) ~[modmenu-1.16.4.jar:?]
	at net.minecraft.class_339.method_25394(class_339.java:86) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen$1.method_25394(ModsScreen.java:150) ~[modmenu-1.16.4.jar:?]
	at net.minecraft.class_437.method_25394(class_437.java:81) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:339) ~[modmenu-1.16.4.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:616) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	... 10 more
```

Running the following: Fabric Loader 0.11.1-1.16.5, Fabric API 0.30.0-1.16, ModMenu 1.16.4 for 1.16.5, ToolTipFix 1.0.2-1.16.1

Issue occurs when opening Mod Options setting box shown below:

https://cdn.discordapp.com/attachments/621951511865327647/806380393430646815/2.PNG

**Comment by kyrptonaught** [comment]
You’re using the 1.16.1 build on 1.16.5, this release was a back port and is not compatible with newer releases. The 1.16 build will work on the newer releases.
